### model
model_name_or_path: /root/vln/LLaMA-Factory/models/LLM-Research/Meta-Llama-3-70B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: r2r_vln_fineturn
template: llama3
cutoff_len: 1024
max_samples: 5000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-70b/lora/sft
logging_steps: 10
save_steps: 120
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 30
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 120